# Server
server.port=8090

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/newdb
spring.datasource.username=postgres
spring.datasource.password=tokyo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8




app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwtExpirationMs=86400000


session_key=c69ed3717b72545ec55d7dd59da021d10db014da1e158f4a1df2a89252f81cab





# Gemini API Configuration
gemini.api.key=AIzaSyB_bPifGUywgsAcwXcnkW4TCC6MkjykRjc







spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=/tmp



spring.thymeleaf.cache=false

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aminegaming275@gmail.com
spring.mail.password=mznnpqlrmauolgjt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000